import { spawn } from 'child_process';
import path from 'path';
import fs from 'fs';
import chalk from 'chalk';
import dotenv from 'dotenv';

interface DevOptions {
    input?: string;
}

export async function dev(file: string, options: DevOptions) {
    // Resolve the workflow file path
    const filePath = path.resolve(file);
    if (!fs.existsSync(filePath)) {
        console.error(chalk.red(`File not found: ${filePath}`));
        process.exit(1);
    }

    // Find the project root (directory containing package.json)
    const projectDir = findProjectRoot(filePath);
    if (!projectDir) {
        console.error(chalk.red('Could not find package.json in parent directories.'));
        process.exit(1);
    }

    // Check that @solidactions/sdk is installed
    const sdkPath = path.join(projectDir, 'node_modules', '@solidactions', 'sdk');
    if (!fs.existsSync(sdkPath)) {
        console.error(chalk.red('@solidactions/sdk is not installed in this project.'));
        console.log(chalk.gray('Run: npm install @solidactions/sdk'));
        process.exit(1);
    }

    // Check that the testing export exists
    const testingPath = path.join(sdkPath, 'dist', 'src', 'testing');
    if (!fs.existsSync(testingPath)) {
        console.error(chalk.red('@solidactions/sdk version does not include testing utilities.'));
        console.log(chalk.gray('Update to the latest SDK version: npm install @solidactions/sdk@latest'));
        process.exit(1);
    }

    // Load .env file from project root
    const envPath = path.join(projectDir, '.env');
    if (fs.existsSync(envPath)) {
        dotenv.config({ path: envPath });
        console.log(chalk.gray(`Loaded .env from ${projectDir}`));
    }

    // Validate input JSON if provided
    const input = options.input || '{}';
    try {
        JSON.parse(input);
    } catch {
        console.error(chalk.red('Invalid JSON input. Use -i \'{"key": "value"}\''));
        process.exit(1);
    }

    // Write temp bootstrap file
    const bootstrapPath = path.join(projectDir, '.solidactions-dev-bootstrap.mjs');
    const bootstrapContent = generateBootstrap(filePath, input);

    try {
        fs.writeFileSync(bootstrapPath, bootstrapContent);

        console.log(chalk.blue('SolidActions local dev mode'));
        console.log(chalk.gray(`File:  ${path.relative(projectDir, filePath)}`));
        console.log(chalk.gray(`Input: ${input}`));
        console.log(chalk.gray('---'));

        // Spawn npx tsx with the bootstrap file
        const child = spawn('npx', ['tsx', bootstrapPath], {
            stdio: 'inherit',
            cwd: projectDir,
        });

        child.on('error', (err) => {
            cleanup(bootstrapPath);
            if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
                console.error(chalk.red('npx not found. Make sure Node.js is installed.'));
            } else {
                console.error(chalk.red(`Failed to start: ${err.message}`));
            }
            process.exit(1);
        });

        child.on('exit', (code) => {
            cleanup(bootstrapPath);
            process.exit(code ?? 1);
        });

        // Also clean up on signals
        process.on('SIGINT', () => {
            cleanup(bootstrapPath);
            child.kill('SIGINT');
        });
        process.on('SIGTERM', () => {
            cleanup(bootstrapPath);
            child.kill('SIGTERM');
        });

    } catch (err: any) {
        cleanup(bootstrapPath);
        console.error(chalk.red(`Failed: ${err.message}`));
        process.exit(1);
    }
}

function generateBootstrap(workflowFile: string, input: string): string {
    // Use forward slashes for the import path (works cross-platform in ESM)
    const importPath = workflowFile.replace(/\\/g, '/');

    return `// Auto-generated by solidactions dev - do not commit
import { createMockServer } from '@solidactions/sdk/testing';
import { SolidActions } from '@solidactions/sdk';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';
import { randomUUID } from 'node:crypto';

const server = await createMockServer();

process.env.SOLIDACTIONS_API_URL = server.baseUrl;
process.env.SOLIDACTIONS_API_KEY ??= 'local-dev';
process.env.SOLIDACTIONS_RUN_ID ??= randomUUID();
process.env.STEPS_TRIGGER_ID ??= 'local-dev';
process.env.SOLIDACTIONS__APPID ??= 'local-dev';
process.env.SOLIDACTIONS__APPVERSION ??= '0';
process.env.WORKFLOW_INPUT = ${JSON.stringify(input)};

// Import the workflow file — pure modules only populate the registry (no top-level run())
await import(${JSON.stringify(importPath)});

// Access the SDK-internal registry via createRequire (bypasses the exports map which
// intentionally does not re-export __getRegisteredWorkflows as a public API — but the
// bootstrap is a CLI-internal glue layer that IS allowed to use these internals).
// The require() resolution path: find the @solidactions/sdk package root by resolving
// the public entry point, then navigate to the registry sibling.
const _require = createRequire(import.meta.url);
const sdkMain = _require.resolve('@solidactions/sdk');
// sdkMain = .../node_modules/@solidactions/sdk/dist/src/index.js
// registry = .../node_modules/@solidactions/sdk/dist/src/invoke/registry.js
const registryPath = resolve(sdkMain, '..', 'invoke', 'registry.js');
const { __getRegisteredWorkflows, __getRegisteredWorkflow } = _require(registryPath);

// Select and run: mirror the SDK launcher's selectWorkflow logic
const all = __getRegisteredWorkflows();
let descriptor;
if (all.length === 1) {
  descriptor = all[0];
} else if (all.length === 0) {
  console.error('solidactions dev: no workflows registered after importing the file.');
  console.error('Make sure the file calls defineWorkflow(...) or SolidActions.registerWorkflow(...).');
  process.exit(1);
} else {
  // Multiple registrations: use WORKFLOW_ID env or fall back to first
  const workflowId = process.env.WORKFLOW_ID;
  const hit = workflowId ? __getRegisteredWorkflow(workflowId) : undefined;
  descriptor = hit ?? all[0];
  if (workflowId && !hit) {
    console.warn('solidactions dev: WORKFLOW_ID "' + workflowId + '" not found; running first registered workflow: ' + (all[0].name ?? '<unnamed>'));
  } else if (!workflowId && all.length > 1) {
    console.warn('solidactions dev: multiple workflows registered; running first: ' + (all[0].name ?? '<unnamed>') + '. Set WORKFLOW_ID env var to select a specific one.');
  }
}

// SolidActions.run() executes the workflow body via the one-shot invoke() engine
// and calls process.exit() when done.
await SolidActions.run(descriptor);
`;
}

function findProjectRoot(startPath: string): string | null {
    let dir = path.dirname(startPath);
    for (let i = 0; i < 10; i++) {
        if (fs.existsSync(path.join(dir, 'package.json'))) {
            return dir;
        }
        const parent = path.dirname(dir);
        if (parent === dir) break;
        dir = parent;
    }
    return null;
}

function cleanup(filePath: string) {
    try {
        if (fs.existsSync(filePath)) {
            fs.unlinkSync(filePath);
        }
    } catch {
        // Ignore cleanup errors
    }
}
