import { spawn } from 'child_process';
import path from 'path';
import fs from 'fs';
import chalk from 'chalk';

interface DevOptions {
    input?: string;
}

export async function dev(file: string, options: DevOptions) {
    // Resolve the workflow file path
    const filePath = path.resolve(file);
    if (!fs.existsSync(filePath)) {
        console.error(chalk.red(`File not found: ${filePath}`));
        process.exit(1);
    }

    // Find the project root (directory containing package.json)
    const projectDir = findProjectRoot(filePath);
    if (!projectDir) {
        console.error(chalk.red('Could not find package.json in parent directories.'));
        process.exit(1);
    }

    // Check that @solidactions/sdk is installed
    const sdkPath = path.join(projectDir, 'node_modules', '@solidactions', 'sdk');
    if (!fs.existsSync(sdkPath)) {
        console.error(chalk.red('@solidactions/sdk is not installed in this project.'));
        console.log(chalk.gray('Run: npm install @solidactions/sdk'));
        process.exit(1);
    }

    // Check that the testing export exists
    const testingPath = path.join(sdkPath, 'dist', 'src', 'testing');
    if (!fs.existsSync(testingPath)) {
        console.error(chalk.red('@solidactions/sdk version does not include testing utilities.'));
        console.log(chalk.gray('Update to the latest SDK version: npm install @solidactions/sdk@latest'));
        process.exit(1);
    }

    // Validate input JSON if provided
    const input = options.input || '{}';
    try {
        JSON.parse(input);
    } catch {
        console.error(chalk.red('Invalid JSON input. Use -i \'{"key": "value"}\''));
        process.exit(1);
    }

    // Write temp bootstrap file
    const bootstrapPath = path.join(projectDir, '.solidactions-dev-bootstrap.mjs');
    const bootstrapContent = generateBootstrap(filePath, input);

    try {
        fs.writeFileSync(bootstrapPath, bootstrapContent);

        console.log(chalk.blue('SolidActions local dev mode'));
        console.log(chalk.gray(`File:  ${path.relative(projectDir, filePath)}`));
        console.log(chalk.gray(`Input: ${input}`));
        console.log(chalk.gray('---'));

        // Spawn npx tsx with the bootstrap file
        const child = spawn('npx', ['tsx', bootstrapPath], {
            stdio: 'inherit',
            cwd: projectDir,
        });

        child.on('error', (err) => {
            cleanup(bootstrapPath);
            if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
                console.error(chalk.red('npx not found. Make sure Node.js is installed.'));
            } else {
                console.error(chalk.red(`Failed to start: ${err.message}`));
            }
            process.exit(1);
        });

        child.on('exit', (code) => {
            cleanup(bootstrapPath);
            process.exit(code ?? 1);
        });

        // Also clean up on signals
        process.on('SIGINT', () => {
            cleanup(bootstrapPath);
            child.kill('SIGINT');
        });
        process.on('SIGTERM', () => {
            cleanup(bootstrapPath);
            child.kill('SIGTERM');
        });

    } catch (err: any) {
        cleanup(bootstrapPath);
        console.error(chalk.red(`Failed: ${err.message}`));
        process.exit(1);
    }
}

function generateBootstrap(workflowFile: string, input: string): string {
    // Use forward slashes for the import path (works cross-platform in ESM)
    const importPath = workflowFile.replace(/\\/g, '/');

    return `// Auto-generated by solidactions dev - do not commit
import { createMockServer } from '@solidactions/sdk/testing';

const server = await createMockServer();

process.env.SOLIDACTIONS_API_URL = server.baseUrl;
process.env.SOLIDACTIONS_API_KEY = 'local-dev';
process.env.WORKFLOW_INPUT = ${JSON.stringify(input)};

// Import the workflow file - this triggers SolidActions.run() at module level
await import(${JSON.stringify(importPath)});
`;
}

function findProjectRoot(startPath: string): string | null {
    let dir = path.dirname(startPath);
    for (let i = 0; i < 10; i++) {
        if (fs.existsSync(path.join(dir, 'package.json'))) {
            return dir;
        }
        const parent = path.dirname(dir);
        if (parent === dir) break;
        dir = parent;
    }
    return null;
}

function cleanup(filePath: string) {
    try {
        if (fs.existsSync(filePath)) {
            fs.unlinkSync(filePath);
        }
    } catch {
        // Ignore cleanup errors
    }
}
