import fs from 'fs';
import path from 'path';
import axios from 'axios';
import chalk from 'chalk';
import readline from 'readline';
import { getConfig } from './init';

interface EnvPullOptions {
    env?: string;
    output?: string;
    yes?: boolean;
}

/**
 * Prompt the user for confirmation (unless --yes flag is set).
 */
async function confirm(message: string): Promise<boolean> {
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
    });

    return new Promise((resolve) => {
        rl.question(`${message} [y/n]: `, (answer) => {
            rl.close();
            resolve(answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes');
        });
    });
}

export async function envPull(projectName: string, options: EnvPullOptions = {}) {
    const config = getConfig();
    if (!config?.apiKey) {
        console.error(chalk.red('Not initialized. Run "solidactions init <api-key>" first.'));
        process.exit(1);
    }

    const environment = options.env || 'production';

    // Build the project slug for lookup
    const projectSlug = environment === 'production'
        ? projectName
        : `${projectName}-${environment}`;

    // Determine output file
    const outputFile = options.output || (environment === 'production' ? '.env' : `.env.${environment}`);
    const outputPath = path.resolve(outputFile);

    console.log(chalk.blue(`Pulling environment variables from "${projectName}" (${environment})...`));

    try {
        // First, check if there are any secrets
        const checkResponse = await axios.get(`${config.host}/api/v1/projects/${projectSlug}/variable-mappings`, {
            headers: {
                'Authorization': `Bearer ${config.apiKey}`,
                'Accept': 'application/json',
            },
        });

        const mappings = checkResponse.data || [];

        if (mappings.length === 0) {
            console.log(chalk.yellow('No environment variables found for this project.'));
            process.exit(0);
        }

        // Check for secrets
        const hasSecrets = mappings.some((m: any) => m.is_secret);

        if (hasSecrets && !options.yes) {
            console.log(chalk.yellow('\nThis project contains secret values.'));
            const confirmed = await confirm('This will expose secret values in plain text. Continue?');
            if (!confirmed) {
                console.log(chalk.gray('Cancelled.'));
                process.exit(0);
            }
        }

        // Now fetch with reveal=true to get actual values
        const response = await axios.get(`${config.host}/api/v1/projects/${projectSlug}/variable-mappings?reveal=true`, {
            headers: {
                'Authorization': `Bearer ${config.apiKey}`,
                'Accept': 'application/json',
            },
        });

        const variables = response.data || [];

        // Build .env file content
        const lines: string[] = [];
        lines.push(`# Environment variables for ${projectName} (${environment})`);
        lines.push(`# Generated by solidactions env:pull on ${new Date().toISOString()}`);
        lines.push('');

        let count = 0;
        let secretCount = 0;

        for (const variable of variables) {
            const key = variable.env_name;
            const value = variable.value;

            if (value === null || value === undefined) {
                // Skip variables with no value
                lines.push(`# ${key}= (no value configured)`);
                continue;
            }

            // Quote values that contain special characters
            let formattedValue = value;
            if (typeof value === 'string' && (
                value.includes(' ') ||
                value.includes('"') ||
                value.includes("'") ||
                value.includes('\n') ||
                value.includes('=') ||
                value.includes('#')
            )) {
                // Escape double quotes and wrap in double quotes
                formattedValue = `"${value.replace(/"/g, '\\"')}"`;
            }

            lines.push(`${key}=${formattedValue}`);
            count++;

            if (variable.is_secret) {
                secretCount++;
            }
        }

        lines.push('');

        // Write to file
        fs.writeFileSync(outputPath, lines.join('\n'));

        console.log(chalk.green(`\n✓ Wrote ${count} variables to ${outputFile}`));
        if (secretCount > 0) {
            console.log(chalk.yellow(`  (includes ${secretCount} secret value${secretCount > 1 ? 's' : ''})`));
        }

    } catch (error: any) {
        if (error.response) {
            if (error.response.status === 401) {
                console.error(chalk.red('Authentication failed. Run "solidactions init <api-key>" to re-configure.'));
            } else if (error.response.status === 404) {
                console.error(chalk.red(`Project "${projectSlug}" not found.`));
                if (environment !== 'production') {
                    console.log(chalk.gray(`Try deploying with: solidactions deploy ${projectName} --env ${environment} --create`));
                }
            } else {
                console.error(chalk.red(`Failed: ${error.response.status}`), error.response.data);
            }
        } else {
            console.error(chalk.red('Connection failed:'), error.message);
        }
        process.exit(1);
    }
}
